export const LOAD_INGREDIENTS = 'LOAD_INGREDIENTS';
export const LOAD_CONSTRUCTOR = 'LOAD_CONSTRUCTOR';
export const LOAD_DETAILS = 'LOAD_DETAILS';
export const DELETE_DETAILS = 'DELETE_DETAILS';
export const ORDER_NUMBER = 'ORDER_NUMBER';
